
### Server properties
server:
  port: 8020
  
### Application Properties 
spring:
  application:
    name: myekart-order-service
    
    
### Datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/myekart_orders?useSSL=false
    username: root
    password: root123
    
### Flyway properties   
  flyway:
    table: myekart_orders_schema_version
    locations: classpath:db/migration
    placeholder-replacement: false
    encoding: UTF-8
    enabled: true
    
## URL Details
service: 
  admin: http://localhost:8010
  item-inventory: http://localhost:8015
  orders: http://localhost:8020