server:
  port: 8000
 
spring:
  application:
    name: novopay-api-gateway
    
## ZUUL Routes configuration
zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    users:
      path: /users/**
      url: http://localhost:8010/users
    inventory:
      path: /inventory/**
      url: http://localhost:8015/inventory
    orders:
      path: /orders/**
      url: http://localhost:8020/orders
